// GENERATED by scripts/search-index.mjs — do not edit.
export default [
  {
    "href": "/api",
    "title": "API reference",
    "group": "Reference"
  },
  {
    "href": "/api#gleanql-core",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/core"
  },
  {
    "href": "/api#gleanql-compiler",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/compiler"
  },
  {
    "href": "/api#gleanql-client-runtime",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/client (runtime)"
  },
  {
    "href": "/api#gleanql-client-client-generated-hooks",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/client/client (generated hooks)"
  },
  {
    "href": "/api#gleanql-vite",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/vite"
  },
  {
    "href": "/architecture",
    "title": "Architecture & pipeline",
    "group": "Guide"
  },
  {
    "href": "/architecture#responsibility-split",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "Responsibility split"
  },
  {
    "href": "/architecture#the-packages",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "The packages"
  },
  {
    "href": "/architecture#the-compile-pipeline",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "The compile pipeline"
  },
  {
    "href": "/architecture#worked-example",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "Worked example"
  },
  {
    "href": "/architecture#compiler-vs-runtime-authority-hybrid",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "Compiler vs. runtime authority (hybrid)"
  },
  {
    "href": "/architecture#the-backend-seam",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "The backend seam"
  },
  {
    "href": "/codegen",
    "title": "@gleanql/codegen",
    "group": "Packages"
  },
  {
    "href": "/codegen#inputs-outputs",
    "title": "@gleanql/codegen",
    "group": "Packages",
    "heading": "Inputs & outputs"
  },
  {
    "href": "/codegen#usage",
    "title": "@gleanql/codegen",
    "group": "Packages",
    "heading": "Usage"
  },
  {
    "href": "/codegen#why-branded-types",
    "title": "@gleanql/codegen",
    "group": "Packages",
    "heading": "Why branded types"
  },
  {
    "href": "/codegen#loop-closure",
    "title": "@gleanql/codegen",
    "group": "Packages",
    "heading": "Loop closure"
  },
  {
    "href": "/comparison",
    "title": "vs Relay & gqty",
    "group": "Guide"
  },
  {
    "href": "/comparison#the-axis-that-actually-matters",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "The axis that actually matters"
  },
  {
    "href": "/comparison#feature-matrix",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "Feature matrix"
  },
  {
    "href": "/comparison#what-compiled-prop-flow-replaces-fragments-with",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "What \"compiled prop flow\" replaces fragments with"
  },
  {
    "href": "/comparison#when-to-choose-what",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "When to choose what"
  },
  {
    "href": "/comparison#receipts",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "Receipts"
  },
  {
    "href": "/compiler",
    "title": "@gleanql/compiler",
    "group": "Packages"
  },
  {
    "href": "/compiler#entry-points",
    "title": "@gleanql/compiler",
    "group": "Packages",
    "heading": "Entry points"
  },
  {
    "href": "/compiler#how-graph-types-are-recognized",
    "title": "@gleanql/compiler",
    "group": "Packages",
    "heading": "How graph types are recognized"
  },
  {
    "href": "/compiler#the-analyzer",
    "title": "@gleanql/compiler",
    "group": "Packages",
    "heading": "The analyzer"
  },
  {
    "href": "/compiler#supported-subset-v1",
    "title": "@gleanql/compiler",
    "group": "Packages",
    "heading": "Supported subset (v1)"
  },
  {
    "href": "/compiler#variables-argument-capture",
    "title": "@gleanql/compiler",
    "group": "Packages",
    "heading": "Variables & argument capture"
  },
  {
    "href": "/compiler#dynamic-components-tiers",
    "title": "@gleanql/compiler",
    "group": "Packages",
    "heading": "Dynamic components (tiers)"
  },
  {
    "href": "/compiler#interfaces-unions",
    "title": "@gleanql/compiler",
    "group": "Packages",
    "heading": "Interfaces & unions"
  },
  {
    "href": "/compiler#lazy-boundaries",
    "title": "@gleanql/compiler",
    "group": "Packages",
    "heading": "Lazy boundaries"
  },
  {
    "href": "/compiler#diagnostics",
    "title": "@gleanql/compiler",
    "group": "Packages",
    "heading": "Diagnostics"
  },
  {
    "href": "/core",
    "title": "@gleanql/core",
    "group": "Packages"
  },
  {
    "href": "/core#query-ir",
    "title": "@gleanql/core",
    "group": "Packages",
    "heading": "Query IR"
  },
  {
    "href": "/core#the-q-builder",
    "title": "@gleanql/core",
    "group": "Packages",
    "heading": "The q. builder"
  },
  {
    "href": "/core#the-selection-merger",
    "title": "@gleanql/core",
    "group": "Packages",
    "heading": "The selection merger"
  },
  {
    "href": "/core#graphql-printer",
    "title": "@gleanql/core",
    "group": "Packages",
    "heading": "GraphQL printer"
  },
  {
    "href": "/core#schema-model",
    "title": "@gleanql/core",
    "group": "Packages",
    "heading": "Schema model"
  },
  {
    "href": "/core#operation-artifact",
    "title": "@gleanql/core",
    "group": "Packages",
    "heading": "Operation artifact"
  },
  {
    "href": "/core#devtools",
    "title": "@gleanql/core",
    "group": "Packages",
    "heading": "Devtools"
  },
  {
    "href": "/core#human-authored-escape-hatch",
    "title": "@gleanql/core",
    "group": "Packages",
    "heading": "Human-authored escape hatch"
  },
  {
    "href": "/core#directives",
    "title": "@gleanql/core",
    "group": "Packages",
    "heading": "Directives"
  },
  {
    "href": "/decisions",
    "title": "Design decisions",
    "group": "Reference"
  },
  {
    "href": "/decisions#consistent-typename-injection",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Consistent typename injection"
  },
  {
    "href": "/decisions#ttsc-backend-the-typescript-compiler-api",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "ttsc backend = the typescript compiler API"
  },
  {
    "href": "/decisions#graphql-graphql-js-is-a-test-only-dependency",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "graphql (graphql-js) is a test-only dependency"
  },
  {
    "href": "/decisions#hybrid-authority-in-v1",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Hybrid authority in v1"
  },
  {
    "href": "/decisions#mutations-compile-like-reads-no-schema-convention-in-core",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Mutations compile like reads — no schema convention in core"
  },
  {
    "href": "/decisions#list-root-membership-is-a-runtime-primitive-not-a-compiler-convention",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "List-root membership is a runtime primitive, not a compiler convention"
  },
  {
    "href": "/decisions#fine-grained-reactivity-via-version-counters-an-affected-key-digest-valtio-style",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Fine-grained reactivity via version counters + an affected-key digest (valtio-style)"
  },
  {
    "href": "/decisions#subscriptions-compile-like-mutations-transport-stays-behind-the-adapter",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Subscriptions compile like mutations; transport stays behind the adapter"
  },
  {
    "href": "/decisions#deliberately-deferred",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Deliberately deferred"
  },
  {
    "href": "/decisions#defer-stream-a-decision-not-yet-a-feature",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "@defer / @stream: a decision, not (yet) a feature"
  },
  {
    "href": "/decisions#testing-strategy",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Testing strategy"
  },
  {
    "href": "/get-started",
    "title": "Get started",
    "group": "Guide"
  },
  {
    "href": "/get-started#1-install",
    "title": "Get started",
    "group": "Guide",
    "heading": "1 · Install"
  },
  {
    "href": "/get-started#2-point-the-plugin-at-your-schema",
    "title": "Get started",
    "group": "Guide",
    "heading": "2 · Point the plugin at your schema"
  },
  {
    "href": "/get-started#3-write-a-component-field-access-is-the-query",
    "title": "Get started",
    "group": "Guide",
    "heading": "3 · Write a component — field access is the query"
  },
  {
    "href": "/get-started#4-run-it",
    "title": "Get started",
    "group": "Guide",
    "heading": "4 · Run it"
  },
  {
    "href": "/get-started#5-turn-the-production-knobs-when-you-want-them",
    "title": "Get started",
    "group": "Guide",
    "heading": "5 · Turn the production knobs (when you want them)"
  },
  {
    "href": "/get-started#where-next",
    "title": "Get started",
    "group": "Guide",
    "heading": "Where next"
  },
  {
    "href": "/golden-cases",
    "title": "Golden cases",
    "group": "Reference"
  },
  {
    "href": "/golden-cases#basic-root",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Basic Root"
  },
  {
    "href": "/golden-cases#deduped",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Deduped"
  },
  {
    "href": "/golden-cases#nested-merge",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Nested Merge"
  },
  {
    "href": "/golden-cases#alias-tracking",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Alias Tracking"
  },
  {
    "href": "/golden-cases#destructuring",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Destructuring"
  },
  {
    "href": "/golden-cases#multiple-roots",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Multiple Roots"
  },
  {
    "href": "/golden-cases#callable-args",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Callable Args"
  },
  {
    "href": "/golden-cases#conflicting-args",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Conflicting Args"
  },
  {
    "href": "/golden-cases#object-truthiness",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Object Truthiness"
  },
  {
    "href": "/golden-cases#union-narrowing",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Union Narrowing"
  },
  {
    "href": "/golden-cases#dynamic-field-access",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Dynamic Field Access"
  },
  {
    "href": "/golden-cases#unknown-dynamic-component",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Unknown Dynamic Component"
  },
  {
    "href": "/golden-cases#variable-factory",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Variable Factory"
  },
  {
    "href": "/golden-cases#list-filter",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "List Filter"
  },
  {
    "href": "/golden-cases#scalar-method",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Scalar Method"
  },
  {
    "href": "/golden-cases#object-spread",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Object Spread"
  },
  {
    "href": "/golden-cases#static-dynamic-component",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Static Dynamic Component"
  },
  {
    "href": "/golden-cases#component-registry",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Component Registry"
  },
  {
    "href": "/golden-cases#lazy-boundary",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Lazy Boundary"
  },
  {
    "href": "/golden-cases#recursive-component",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Recursive Component"
  },
  {
    "href": "/golden-cases#split-file-components",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Split File Components"
  },
  {
    "href": "/golden-cases#path-alias",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Path Alias"
  },
  {
    "href": "/golden-cases#helper-functions",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Helper Functions"
  },
  {
    "href": "/golden-cases#nonnull-arg",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Nonnull Arg"
  },
  {
    "href": "/golden-cases#island-reads",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Island Reads"
  },
  {
    "href": "/golden-cases#mutation",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Mutation"
  },
  {
    "href": "/golden-cases#subscription",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Subscription"
  },
  {
    "href": "/golden-cases#chained-root",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Chained Root"
  },
  {
    "href": "/golden-cases#map-block-binding",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Map Block Binding"
  },
  {
    "href": "/golden-cases#island-map-component",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Island Map Component"
  },
  {
    "href": "/golden-cases#list-root",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "List Root"
  },
  {
    "href": "/golden-cases#map-named-callback",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Map Named Callback"
  },
  {
    "href": "/golden-cases#map-destructured-param",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Map Destructured Param"
  },
  {
    "href": "/golden-cases#unsupported-list-callback",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Unsupported List Callback"
  },
  {
    "href": "/golden-cases#shared-param",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Shared Param"
  },
  {
    "href": "/golden-cases#acceptance",
    "title": "Golden cases",
    "group": "Reference",
    "heading": "Acceptance"
  },
  {
    "href": "/index",
    "title": "Overview",
    "group": "Guide"
  },
  {
    "href": "/index#the-idea-in-one-screen",
    "title": "Overview",
    "group": "Guide",
    "heading": "The idea in one screen"
  },
  {
    "href": "/index#everything-else-follows-the-same-rule",
    "title": "Overview",
    "group": "Guide",
    "heading": "Everything else follows the same rule"
  },
  {
    "href": "/index#the-packages",
    "title": "Overview",
    "group": "Guide",
    "heading": "The packages"
  },
  {
    "href": "/index#how-a-build-works",
    "title": "Overview",
    "group": "Guide",
    "heading": "How a build works"
  },
  {
    "href": "/index#where-to-go",
    "title": "Overview",
    "group": "Guide",
    "heading": "Where to go"
  },
  {
    "href": "/react-router",
    "title": "React Router integration",
    "group": "Integrations"
  },
  {
    "href": "/react-router#the-one-seam-a-shared-scope",
    "title": "React Router integration",
    "group": "Integrations",
    "heading": "The one seam: a shared scope"
  },
  {
    "href": "/react-router#setup",
    "title": "React Router integration",
    "group": "Integrations",
    "heading": "Setup"
  },
  {
    "href": "/react-router#per-request-the-loader-render-handoff",
    "title": "React Router integration",
    "group": "Integrations",
    "heading": "Per request — the loader→render handoff"
  },
  {
    "href": "/react-router#serialize-hydrate-loader-data-not-a-script",
    "title": "React Router integration",
    "group": "Integrations",
    "heading": "Serialize & hydrate (loader data, not a script)"
  },
  {
    "href": "/react-router#components-islands",
    "title": "React Router integration",
    "group": "Integrations",
    "heading": "Components & islands"
  },
  {
    "href": "/react-router#the-real-app-zero-glue",
    "title": "React Router integration",
    "group": "Integrations",
    "heading": "The real app — zero glue"
  },
  {
    "href": "/react-router#why-it-works-without-an-adapter-package",
    "title": "React Router integration",
    "group": "Integrations",
    "heading": "Why it works without an adapter package"
  },
  {
    "href": "/runtime",
    "title": "@gleanql/client",
    "group": "Packages"
  },
  {
    "href": "/runtime#client-adapter-the-only-transport-seam",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Client adapter (the only transport seam)"
  },
  {
    "href": "/runtime#cache-identity-model",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Cache identity model"
  },
  {
    "href": "/runtime#suspense-aware-reads",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Suspense-aware reads"
  },
  {
    "href": "/runtime#reactivity-cache-first-refetch",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Reactivity & cache-first refetch"
  },
  {
    "href": "/runtime#store-retention-gc-reference-counted-relay-style",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Store retention & GC (reference-counted, Relay-style)"
  },
  {
    "href": "/runtime#error-surfaces",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Error surfaces"
  },
  {
    "href": "/runtime#missing-field-batching",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Missing-field batching"
  },
  {
    "href": "/runtime#seeding-result-normalization",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Seeding & result normalization"
  },
  {
    "href": "/runtime#runtime-graph-proxies",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Runtime graph proxies"
  },
  {
    "href": "/runtime#request-scope",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Request scope"
  },
  {
    "href": "/runtime#the-route-flow-framework-seam",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "The route flow (framework seam)"
  },
  {
    "href": "/runtime#hydration-two-models",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Hydration — two models"
  },
  {
    "href": "/runtime#client-side-refresh",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Client-side refresh()"
  },
  {
    "href": "/runtime#list-root-membership-appendtoroot-removefromroot",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "List-root membership (appendToRoot / removeFromRoot)"
  },
  {
    "href": "/runtime#mutations-invalidation",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Mutations & invalidation"
  },
  {
    "href": "/runtime#client-hooks-islands",
    "title": "@gleanql/client",
    "group": "Packages",
    "heading": "Client hooks (islands)"
  },
  {
    "href": "/rwsdk",
    "title": "RedwoodSDK integration",
    "group": "Integrations"
  },
  {
    "href": "/rwsdk#what-an-adapter-answers",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "What an adapter answers"
  },
  {
    "href": "/rwsdk#setup",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "Setup"
  },
  {
    "href": "/rwsdk#per-request",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "Per request"
  },
  {
    "href": "/rwsdk#serialize-hydrate",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "Serialize & hydrate"
  },
  {
    "href": "/rwsdk#boundary-rules",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "Boundary rules"
  },
  {
    "href": "/rwsdk#mutations",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "Mutations"
  },
  {
    "href": "/rwsdk#client-islands-refetch-mixing-client-rsc",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "Client islands & refetch (mixing client + RSC)"
  },
  {
    "href": "/rwsdk#a-mutation-island-writes-update-in-place",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "A mutation island — writes update in place"
  },
  {
    "href": "/rwsdk#the-real-app-zero-glue-gleanql-vite",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "The real app — zero glue (@gleanql/vite)"
  },
  {
    "href": "/rwsdk#in-ci-worker-no-workerd",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "In-CI worker (no workerd)"
  },
  {
    "href": "/rwsdk#status",
    "title": "RedwoodSDK integration",
    "group": "Integrations",
    "heading": "Status"
  },
  {
    "href": "/usage",
    "title": "Using GleanQL",
    "group": "Guide"
  },
  {
    "href": "/usage#reading-data",
    "title": "Using GleanQL",
    "group": "Guide",
    "heading": "Reading data"
  },
  {
    "href": "/usage#writing-data",
    "title": "Using GleanQL",
    "group": "Guide",
    "heading": "Writing data"
  },
  {
    "href": "/usage#staying-live",
    "title": "Using GleanQL",
    "group": "Guide",
    "heading": "Staying live"
  },
  {
    "href": "/usage#hardening-for-production",
    "title": "Using GleanQL",
    "group": "Guide",
    "heading": "Hardening for production"
  },
  {
    "href": "/usage#where-to-go-next",
    "title": "Using GleanQL",
    "group": "Guide",
    "heading": "Where to go next"
  },
  {
    "href": "/vite",
    "title": "@gleanql/vite",
    "group": "Packages"
  },
  {
    "href": "/vite#usage",
    "title": "@gleanql/vite",
    "group": "Packages",
    "heading": "Usage"
  },
  {
    "href": "/vite#what-it-does-on-startup",
    "title": "@gleanql/vite",
    "group": "Packages",
    "heading": "What it does on startup"
  },
  {
    "href": "/vite#plugin-options",
    "title": "@gleanql/vite",
    "group": "Packages",
    "heading": "Plugin options"
  },
  {
    "href": "/vite#devtools-glean-live-recompilation",
    "title": "@gleanql/vite",
    "group": "Packages",
    "heading": "Devtools (/glean) & live recompilation"
  },
  {
    "href": "/vite#type-check-backend-typescript-tsgo",
    "title": "@gleanql/vite",
    "group": "Packages",
    "heading": "Type-check backend (typescript / tsgo)"
  },
  {
    "href": "/vite#framework-presets",
    "title": "@gleanql/vite",
    "group": "Packages",
    "heading": "Framework presets"
  },
  {
    "href": "/vite#generated-glue-thin-shims-over-typed-factories",
    "title": "@gleanql/vite",
    "group": "Packages",
    "heading": "Generated glue: thin shims over typed factories"
  },
  {
    "href": "/vite#build",
    "title": "@gleanql/vite",
    "group": "Packages",
    "heading": "Build"
  }
] as const;
