/**
 * Slim runtime schema — emit only what the runtime can ever touch.
 *
 * The build compiles routes against the FULL schema model (in memory, from the
 * SDL), but the emitted `generated/schema-model.js` is consumed at runtime
 * only, and the runtime's schema surface is bounded by the compiled
 * operations: `identityOf` (normalization keys), proxy navigation
 * (`getField`/`getType` along read paths), and `usePaginated`'s connection
 * trails (field defs + arg types on selection paths). Every one of those walks
 * fields that appear in a compiled selection.
 *
 * So instead of shipping the whole schema (3,000 types for Shopify's Admin
 * API ≈ ~1MB of source riding into a worker bundle), emit the subset
 * reachable from the compiled selections:
 *
 *   - every type a selection set evaluates against (+ inline-fragment types),
 *     with only the selected fields — plus the type's identity fields, which
 *     the runtime keys records by even when unread
 *   - name+kind stubs for the named types of kept fields, so leaf checks
 *     (`isLeaf`/`isObjectLike`) classify correctly
 *
 * Reads OUTSIDE the compiled selections can't be classified by this model —
 * which is by design: every read is supposed to be in a compiled operation
 * (that's the compiler's whole contract, and `masking` warns when a component
 * strays). `fetchMissing` still serves lazy boundaries and other misses on
 * fields the operations DO select.
 */
import type {
  FieldDef,
  OperationArtifact,
  SchemaModel,
  SchemaModelInit,
  SelectionSet,
  TypeDef,
} from "@gleanql/core";

/** Collect `typeName -> selected field names` over every compiled selection. */
function collectSelectedFields(
  operations: Record<string, OperationArtifact>,
): Map<string, Set<string>> {
  const used = new Map<string, Set<string>>();
  const visit = (sel: SelectionSet): void => {
    let fields = used.get(sel.typeName);
    if (!fields) used.set(sel.typeName, (fields = new Set()));
    for (const field of sel.fields) {
      fields.add(field.name);
      if (field.selection) visit(field.selection);
    }
    for (const frag of sel.inlineFragments ?? []) visit(frag.selection);
  };
  for (const op of Object.values(operations)) visit(op.selection);
  return used;
}

/** The runtime-reachable subset of `schema`, given the compiled operations. */
export function slimRuntimeSchema(
  schema: SchemaModel,
  operations: Record<string, OperationArtifact>,
): SchemaModelInit {
  const used = collectSelectedFields(operations);
  const types: TypeDef[] = [];
  const included = new Set<string>();
  const stubs = new Set<string>();

  for (const [typeName, fieldNames] of used) {
    const def = schema.getType(typeName);
    if (!def) continue;
    included.add(typeName);

    let fields: Record<string, FieldDef> | undefined;
    if (def.fields) {
      fields = {};
      // Identity fields key normalized records even when no component reads
      // them (the compiler auto-selects them into the document).
      for (const key of [...fieldNames, ...schema.keyFields(typeName)]) {
        const fieldDef = def.fields[key];
        if (fieldDef) {
          fields[key] = fieldDef;
          stubs.add(fieldDef.type);
        }
      }
    }

    types.push({
      name: def.name,
      kind: def.kind,
      ...(def.keys ? { keys: def.keys } : {}),
      ...(def.possibleTypes ? { possibleTypes: def.possibleTypes } : {}),
      ...(fields ? { fields } : {}),
    });
  }

  // name+kind stubs for the named types of kept fields: enough for
  // `isLeaf`/`isObjectLike`, nothing more.
  for (const name of stubs) {
    if (included.has(name)) continue;
    const def = schema.getType(name);
    if (!def) continue;
    included.add(name);
    types.push({ name: def.name, kind: def.kind, ...(def.keys ? { keys: def.keys } : {}) });
  }

  return {
    queryType: schema.queryType,
    ...(schema.mutationType ? { mutationType: schema.mutationType } : {}),
    ...(schema.subscriptionType ? { subscriptionType: schema.subscriptionType } : {}),
    types,
  };
}

/** Render a `SchemaModelInit` as the generated `schema-model.js` module. */
export function renderSlimSchemaModelJs(init: SchemaModelInit): string {
  return [
    "// GENERATED by @gleanql/vite — runtime subset of the schema (see slim-schema.ts).",
    'import { defineSchema } from "@gleanql/core";',
    `export const schema = defineSchema(${JSON.stringify(init, null, 2)});`,
    "",
  ].join("\n");
}
