// GENERATED by scripts/search-index.mjs — do not edit.
export default [
  {
    "href": "/api.html",
    "title": "API reference",
    "group": "Reference"
  },
  {
    "href": "/api.html#gleanql-core",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/core"
  },
  {
    "href": "/api.html#gleanql-compiler",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/compiler"
  },
  {
    "href": "/api.html#gleanql-client-runtime",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/client (runtime)"
  },
  {
    "href": "/api.html#gleanql-client-client-generated-hooks",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/client/client (generated hooks)"
  },
  {
    "href": "/api.html#gleanql-vite",
    "title": "API reference",
    "group": "Reference",
    "heading": "@gleanql/vite"
  },
  {
    "href": "/architecture.html",
    "title": "Architecture & pipeline",
    "group": "Guide"
  },
  {
    "href": "/architecture.html#responsibility-split",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "Responsibility split"
  },
  {
    "href": "/architecture.html#the-packages",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "The packages"
  },
  {
    "href": "/architecture.html#the-compile-pipeline",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "The compile pipeline"
  },
  {
    "href": "/architecture.html#worked-example",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "Worked example"
  },
  {
    "href": "/architecture.html#compiler-vs-runtime-authority-hybrid",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "Compiler vs. runtime authority (hybrid)"
  },
  {
    "href": "/architecture.html#the-backend-seam",
    "title": "Architecture & pipeline",
    "group": "Guide",
    "heading": "The backend seam"
  },
  {
    "href": "/codegen.html",
    "title": "@gleanql/codegen",
    "group": "Internals"
  },
  {
    "href": "/codegen.html#inputs-outputs",
    "title": "@gleanql/codegen",
    "group": "Internals",
    "heading": "Inputs & outputs"
  },
  {
    "href": "/codegen.html#usage",
    "title": "@gleanql/codegen",
    "group": "Internals",
    "heading": "Usage"
  },
  {
    "href": "/codegen.html#why-branded-types",
    "title": "@gleanql/codegen",
    "group": "Internals",
    "heading": "Why branded types"
  },
  {
    "href": "/codegen.html#loop-closure",
    "title": "@gleanql/codegen",
    "group": "Internals",
    "heading": "Loop closure"
  },
  {
    "href": "/comparison.html",
    "title": "vs Relay & gqty",
    "group": "Guide"
  },
  {
    "href": "/comparison.html#the-axis-that-actually-matters",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "The axis that actually matters"
  },
  {
    "href": "/comparison.html#feature-matrix",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "Feature matrix"
  },
  {
    "href": "/comparison.html#what-compiled-prop-flow-replaces-fragments-with",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "What \"compiled prop flow\" replaces fragments with"
  },
  {
    "href": "/comparison.html#when-to-choose-what",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "When to choose what"
  },
  {
    "href": "/comparison.html#receipts",
    "title": "vs Relay & gqty",
    "group": "Guide",
    "heading": "Receipts"
  },
  {
    "href": "/compiler.html",
    "title": "@gleanql/compiler",
    "group": "Internals"
  },
  {
    "href": "/compiler.html#entry-points",
    "title": "@gleanql/compiler",
    "group": "Internals",
    "heading": "Entry points"
  },
  {
    "href": "/compiler.html#how-graph-types-are-recognized",
    "title": "@gleanql/compiler",
    "group": "Internals",
    "heading": "How graph types are recognized"
  },
  {
    "href": "/compiler.html#the-analyzer",
    "title": "@gleanql/compiler",
    "group": "Internals",
    "heading": "The analyzer"
  },
  {
    "href": "/compiler.html#supported-subset-v1",
    "title": "@gleanql/compiler",
    "group": "Internals",
    "heading": "Supported subset (v1)"
  },
  {
    "href": "/compiler.html#variables-argument-capture",
    "title": "@gleanql/compiler",
    "group": "Internals",
    "heading": "Variables & argument capture"
  },
  {
    "href": "/compiler.html#dynamic-components-tiers",
    "title": "@gleanql/compiler",
    "group": "Internals",
    "heading": "Dynamic components (tiers)"
  },
  {
    "href": "/compiler.html#interfaces-unions",
    "title": "@gleanql/compiler",
    "group": "Internals",
    "heading": "Interfaces & unions"
  },
  {
    "href": "/compiler.html#lazy-boundaries",
    "title": "@gleanql/compiler",
    "group": "Internals",
    "heading": "Lazy boundaries"
  },
  {
    "href": "/compiler.html#diagnostics",
    "title": "@gleanql/compiler",
    "group": "Internals",
    "heading": "Diagnostics"
  },
  {
    "href": "/core.html",
    "title": "@gleanql/core",
    "group": "Internals"
  },
  {
    "href": "/core.html#query-ir",
    "title": "@gleanql/core",
    "group": "Internals",
    "heading": "Query IR"
  },
  {
    "href": "/core.html#the-q-builder",
    "title": "@gleanql/core",
    "group": "Internals",
    "heading": "The q.* builder"
  },
  {
    "href": "/core.html#the-selection-merger",
    "title": "@gleanql/core",
    "group": "Internals",
    "heading": "The selection merger"
  },
  {
    "href": "/core.html#graphql-printer",
    "title": "@gleanql/core",
    "group": "Internals",
    "heading": "GraphQL printer"
  },
  {
    "href": "/core.html#schema-model",
    "title": "@gleanql/core",
    "group": "Internals",
    "heading": "Schema model"
  },
  {
    "href": "/core.html#operation-artifact",
    "title": "@gleanql/core",
    "group": "Internals",
    "heading": "Operation artifact"
  },
  {
    "href": "/core.html#devtools",
    "title": "@gleanql/core",
    "group": "Internals",
    "heading": "Devtools"
  },
  {
    "href": "/core.html#human-authored-escape-hatch",
    "title": "@gleanql/core",
    "group": "Internals",
    "heading": "Human-authored escape hatch"
  },
  {
    "href": "/core.html#directives",
    "title": "@gleanql/core",
    "group": "Internals",
    "heading": "Directives"
  },
  {
    "href": "/decisions.html",
    "title": "Design decisions",
    "group": "Reference"
  },
  {
    "href": "/decisions.html#consistent-__typename-injection",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Consistent __typename injection"
  },
  {
    "href": "/decisions.html#ttsc-backend-the-typescript-compiler-api",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "ttsc backend = the typescript compiler API"
  },
  {
    "href": "/decisions.html#graphql-graphql-js-is-a-test-only-dependency",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "graphql (graphql-js) is a test-only dependency"
  },
  {
    "href": "/decisions.html#component-only-brief-examples-are-wrapped-in-a-route",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Component-only brief examples are wrapped in a route"
  },
  {
    "href": "/decisions.html#hybrid-authority-in-v1",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Hybrid authority in v1"
  },
  {
    "href": "/decisions.html#mutations-compile-like-reads-no-schema-convention-in-core",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Mutations compile like reads — no schema convention in core"
  },
  {
    "href": "/decisions.html#list-root-membership-is-a-runtime-primitive-not-a-compiler-convention",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "List-root membership is a runtime primitive, not a compiler convention"
  },
  {
    "href": "/decisions.html#fine-grained-reactivity-via-version-counters-an-affected-key-digest-valtio-style",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Fine-grained reactivity via version counters + an affected-key digest (valtio-style)"
  },
  {
    "href": "/decisions.html#subscriptions-compile-like-mutations-transport-stays-behind-the-adapter",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Subscriptions compile like mutations; transport stays behind the adapter"
  },
  {
    "href": "/decisions.html#deferred-per-the-brief-s-v1-non-goals",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Deferred (per the brief's v1 non-goals)"
  },
  {
    "href": "/decisions.html#defer-stream-a-decision-not-yet-a-feature",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "@defer / @stream: a decision, not (yet) a feature"
  },
  {
    "href": "/decisions.html#testing-strategy",
    "title": "Design decisions",
    "group": "Reference",
    "heading": "Testing strategy"
  },
  {
    "href": "/get-started.html",
    "title": "Get started",
    "group": "Guide"
  },
  {
    "href": "/get-started.html#1-install",
    "title": "Get started",
    "group": "Guide",
    "heading": "1 · Install"
  },
  {
    "href": "/get-started.html#2-point-the-plugin-at-your-schema",
    "title": "Get started",
    "group": "Guide",
    "heading": "2 · Point the plugin at your schema"
  },
  {
    "href": "/get-started.html#3-write-a-component-field-access-is-the-query",
    "title": "Get started",
    "group": "Guide",
    "heading": "3 · Write a component — field access is the query"
  },
  {
    "href": "/get-started.html#4-run-it",
    "title": "Get started",
    "group": "Guide",
    "heading": "4 · Run it"
  },
  {
    "href": "/get-started.html#5-turn-the-production-knobs-when-you-want-them",
    "title": "Get started",
    "group": "Guide",
    "heading": "5 · Turn the production knobs (when you want them)"
  },
  {
    "href": "/get-started.html#where-next",
    "title": "Get started",
    "group": "Guide",
    "heading": "Where next"
  },
  {
    "href": "/golden-cases.html",
    "title": "Golden cases",
    "group": "Reference"
  },
  {
    "href": "/index.html",
    "title": "Overview",
    "group": "Guide"
  },
  {
    "href": "/index.html#the-idea-in-one-screen",
    "title": "Overview",
    "group": "Guide",
    "heading": "The idea in one screen"
  },
  {
    "href": "/index.html#what-this-repository-contains",
    "title": "Overview",
    "group": "Guide",
    "heading": "What this repository contains"
  },
  {
    "href": "/index.html#quick-start",
    "title": "Overview",
    "group": "Guide",
    "heading": "Quick start"
  },
  {
    "href": "/index.html#how-it-fits-together",
    "title": "Overview",
    "group": "Guide",
    "heading": "How it fits together"
  },
  {
    "href": "/react-router.html",
    "title": "React Router integration",
    "group": "Internals"
  },
  {
    "href": "/react-router.html#the-one-seam-a-shared-scope",
    "title": "React Router integration",
    "group": "Internals",
    "heading": "The one seam: a shared scope"
  },
  {
    "href": "/react-router.html#setup",
    "title": "React Router integration",
    "group": "Internals",
    "heading": "Setup"
  },
  {
    "href": "/react-router.html#per-request-the-loader-render-handoff",
    "title": "React Router integration",
    "group": "Internals",
    "heading": "Per request — the loader→render handoff"
  },
  {
    "href": "/react-router.html#serialize-hydrate-loader-data-not-a-script",
    "title": "React Router integration",
    "group": "Internals",
    "heading": "Serialize & hydrate (loader data, not a script)"
  },
  {
    "href": "/react-router.html#components-islands",
    "title": "React Router integration",
    "group": "Internals",
    "heading": "Components & islands"
  },
  {
    "href": "/react-router.html#the-real-app-zero-glue",
    "title": "React Router integration",
    "group": "Internals",
    "heading": "The real app — zero glue"
  },
  {
    "href": "/react-router.html#why-it-works-without-an-adapter-package",
    "title": "React Router integration",
    "group": "Internals",
    "heading": "Why it works without an adapter package"
  },
  {
    "href": "/runtime.html",
    "title": "@gleanql/client",
    "group": "Internals"
  },
  {
    "href": "/runtime.html#client-adapter-the-only-transport-seam",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Client adapter (the only transport seam)"
  },
  {
    "href": "/runtime.html#cache-identity-model",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Cache identity model"
  },
  {
    "href": "/runtime.html#suspense-aware-reads",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Suspense-aware reads"
  },
  {
    "href": "/runtime.html#reactivity-cache-first-refetch",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Reactivity & cache-first refetch"
  },
  {
    "href": "/runtime.html#store-retention-gc-reference-counted-relay-style",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Store retention & GC (reference-counted, Relay-style)"
  },
  {
    "href": "/runtime.html#error-surfaces",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Error surfaces"
  },
  {
    "href": "/runtime.html#missing-field-batching",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Missing-field batching"
  },
  {
    "href": "/runtime.html#seeding-result-normalization",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Seeding & result normalization"
  },
  {
    "href": "/runtime.html#runtime-graph-proxies",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Runtime graph proxies"
  },
  {
    "href": "/runtime.html#request-scope",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Request scope"
  },
  {
    "href": "/runtime.html#the-route-flow-framework-seam",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "The route flow (framework seam)"
  },
  {
    "href": "/runtime.html#hydration-two-models",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Hydration — two models"
  },
  {
    "href": "/runtime.html#client-side-refresh",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Client-side refresh()"
  },
  {
    "href": "/runtime.html#list-root-membership-appendtoroot-removefromroot",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "List-root membership (appendToRoot / removeFromRoot)"
  },
  {
    "href": "/runtime.html#mutations-invalidation",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Mutations & invalidation"
  },
  {
    "href": "/runtime.html#client-hooks-islands",
    "title": "@gleanql/client",
    "group": "Internals",
    "heading": "Client hooks (islands)"
  },
  {
    "href": "/rwsdk.html",
    "title": "RedwoodSDK integration",
    "group": "Internals"
  },
  {
    "href": "/rwsdk.html#what-an-adapter-answers",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "What an adapter answers"
  },
  {
    "href": "/rwsdk.html#setup",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "Setup"
  },
  {
    "href": "/rwsdk.html#per-request",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "Per request"
  },
  {
    "href": "/rwsdk.html#serialize-hydrate",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "Serialize & hydrate"
  },
  {
    "href": "/rwsdk.html#boundary-rules",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "Boundary rules"
  },
  {
    "href": "/rwsdk.html#mutations",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "Mutations"
  },
  {
    "href": "/rwsdk.html#client-islands-refetch-mixing-client-rsc",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "Client islands & refetch (mixing client + RSC)"
  },
  {
    "href": "/rwsdk.html#a-mutation-island-writes-update-in-place",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "A mutation island — writes update in place"
  },
  {
    "href": "/rwsdk.html#the-real-app-zero-glue-gleanql-vite",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "The real app — zero glue (@gleanql/vite)"
  },
  {
    "href": "/rwsdk.html#in-ci-worker-no-workerd",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "In-CI worker (no workerd)"
  },
  {
    "href": "/rwsdk.html#status",
    "title": "RedwoodSDK integration",
    "group": "Internals",
    "heading": "Status"
  },
  {
    "href": "/usage.html",
    "title": "Using Glean",
    "group": "Guide"
  },
  {
    "href": "/usage.html#1-install-wire-up",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "1 · Install & wire up"
  },
  {
    "href": "/usage.html#2-read-data",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "2 · Read data"
  },
  {
    "href": "/usage.html#3-server-components-vs-islands",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "3 · Server components vs. islands"
  },
  {
    "href": "/usage.html#4-lists-list-roots",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "4 · Lists & list roots"
  },
  {
    "href": "/usage.html#5-write-data-mutations",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "5 · Write data (mutations)"
  },
  {
    "href": "/usage.html#6-optimistic-ui",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "6 · Optimistic UI"
  },
  {
    "href": "/usage.html#7-paginate",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "7 · Paginate"
  },
  {
    "href": "/usage.html#8-live-data-subscriptions",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "8 · Live data (subscriptions)"
  },
  {
    "href": "/usage.html#9-refetch",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "9 · Refetch"
  },
  {
    "href": "/usage.html#10-lock-down-the-wire-persisted-operations",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "10 · Lock down the wire (persisted operations)"
  },
  {
    "href": "/usage.html#11-hand-built-operations-dynamic-shapes",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "11 · Hand-built operations (dynamic shapes)"
  },
  {
    "href": "/usage.html#12-handle-errors",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "12 · Handle errors"
  },
  {
    "href": "/usage.html#where-to-go-next",
    "title": "Using Glean",
    "group": "Guide",
    "heading": "Where to go next"
  },
  {
    "href": "/vite.html",
    "title": "@gleanql/vite",
    "group": "Internals"
  },
  {
    "href": "/vite.html#usage",
    "title": "@gleanql/vite",
    "group": "Internals",
    "heading": "Usage"
  },
  {
    "href": "/vite.html#what-it-does-on-startup",
    "title": "@gleanql/vite",
    "group": "Internals",
    "heading": "What it does on startup"
  },
  {
    "href": "/vite.html#plugin-options",
    "title": "@gleanql/vite",
    "group": "Internals",
    "heading": "Plugin options"
  },
  {
    "href": "/vite.html#devtools-__glean-live-recompilation",
    "title": "@gleanql/vite",
    "group": "Internals",
    "heading": "Devtools (/__glean) & live recompilation"
  },
  {
    "href": "/vite.html#type-check-backend-typescript-tsgo",
    "title": "@gleanql/vite",
    "group": "Internals",
    "heading": "Type-check backend (typescript / tsgo)"
  },
  {
    "href": "/vite.html#framework-presets",
    "title": "@gleanql/vite",
    "group": "Internals",
    "heading": "Framework presets"
  },
  {
    "href": "/vite.html#generated-glue-thin-shims-over-typed-factories",
    "title": "@gleanql/vite",
    "group": "Internals",
    "heading": "Generated glue: thin shims over typed factories"
  },
  {
    "href": "/vite.html#build",
    "title": "@gleanql/vite",
    "group": "Internals",
    "heading": "Build"
  }
] as const;
