import type { OperationArtifact, SchemaModel } from "@gleanql/core";
import type { IntrospectionSchema } from "@gleanql/codegen";
import { SCALARS, collectNamed, renderTs, renderTsInner } from "../render.js";
import type { RequestScope } from "../types.js";
import { renderActiveResolver } from "./resolver.js";

/**
 * The runtime `@gleanql/client/generated/index.js`: the request-scoped `graph`
 * accessor (which imports the framework's request scope), re-exporting the
 * portable data. Server code imports this; client islands import the data module.
 */
export function genGeneratedJs(
  schemaModel: SchemaModel,
  _operations: Record<string, OperationArtifact>,
  requestScope: RequestScope = "rwsdk",
): string {
  const rootFields = Object.keys(schemaModel.getType(schemaModel.queryType)?.fields ?? {});
  const accessors = rootFields.map((f) => `  ${f}(args) { return __active().graph.${f}(args); },`).join("\n");

  return `// GENERATED by @gleanql/vite — do not edit.
${renderActiveResolver(requestScope)}
export { schema, operations } from "./operations.js";

export const glean = {
${accessors}
};
`;
}

/** Compute the schema-specific accessor signatures for a root type + the branded types referenced. */
function rootAccessor(
  introspection: IntrospectionSchema,
  rootTypeName: string | undefined,
): { sigs: string[]; imports: string[] } {
  const fields = (rootTypeName ? introspection.types.find((t) => t.name === rootTypeName)?.fields : undefined) ?? [];
  const named = new Set<string>();
  const sigs = fields.map((f) => {
    collectNamed(f.type, named);
    f.args.forEach((a) => collectNamed(a.type, named));
    // The args object is optional when every argument is — `glean.productsCount()`.
    const allOptional = f.args.every((a) => a.type.kind !== "NON_NULL");
    const args = f.args.length
      ? `args${allOptional ? "?" : ""}: { ${f.args.map((a) => `${a.name}${a.type.kind === "NON_NULL" ? "" : "?"}: ${renderTs(a.type)}`).join("; ")} }`
      : "";
    // Roots are non-null in app code: the route interruptor 404s when a root is null.
    return `  ${f.name}(${args}): ${renderTsInner(f.type)};`;
  });
  return { sigs, imports: [...named].filter((n) => !SCALARS[n]).sort() };
}

/**
 * The `@gleanql/client` top-level `index.d.ts`. The runtime API comes from REAL
 * declarations emitted off the source (`./src/index`), so it's complete and
 * always in sync — not a hand-curated subset. This file only adds the
 * schema-specific pieces: the branded types and the typed `graph` accessor.
 */
export function genIndexDts(introspection: IntrospectionSchema, schemaModel: SchemaModel): string {
  const query = rootAccessor(introspection, schemaModel.queryType);
  const mutation = schemaModel.mutationType ? rootAccessor(introspection, schemaModel.mutationType) : undefined;
  const subscription = schemaModel.subscriptionType ? rootAccessor(introspection, schemaModel.subscriptionType) : undefined;
  const imports = [
    ...new Set([...query.imports, ...(mutation?.imports ?? []), ...(subscription?.imports ?? [])]),
  ].sort();

  // The schema-specific root accessor types (gated on the schema exposing each root):
  // one callable per field, so a `useMutation`/`useSubscription` selector typechecks
  // and `data` is inferred from the selected result. Compile-time only — never executed.
  const rootBlock = (name: string, accessor: { sigs: string[] } | undefined, hook: string) =>
    accessor
      ? `

// The schema-specific ${name} accessor type: one callable per ${name.toLowerCase()} field,
// used to type \`${hook}\` selectors (compile-time only — never executed).
export type ${name} = {
${accessor.sigs.join("\n")}
};`
      : "";

  return `// GENERATED — do not edit.
export * from "./src/index.js";        // real runtime API (declarations emitted from source)
export * from "./generated/operations"; // operations + schema (typed)
export * from "./generated/schema";     // branded schema types
import type { ${imports.join(", ")} } from "./generated/schema";

// The schema-specific accessor type: one non-null callable per Query root. Exported
// so islands' \`useGlean()\` is typed with it (no casts needed on graph reads).
export type Graph = {
${query.sigs.join("\n")}
};
export declare const glean: Graph;${rootBlock("Mutation", mutation, "useMutation")}${rootBlock("Subscription", subscription, "useSubscription")}
`;
}
