/**
 * The tiny emit DSL the generated-module renderers share. Generated files stay
 * template strings at the bottom (they read like the output they produce), but
 * every module is assembled from these declarative parts instead of ad-hoc
 * `${cond ? "…" : ""}` concatenation — and every emitter's output is
 * parse-validated by `emit-syntax.test.ts`, so a template typo cannot ship.
 */

const BANNER = "// GENERATED by @gleanql/vite — do not edit.";
const DTS_BANNER = "// GENERATED — do not edit.";

type Line = string | false | undefined;

/** Keep the truthy lines (a `cond && "line"` part simply disappears). */
function lines(parts: readonly Line[]): string[] {
  return parts.filter((p): p is string => typeof p === "string" && p.length > 0);
}

/** A generated runtime module: banner, optional directive, imports, blank line, body. */
export function generatedModule(parts: {
  readonly directive?: string;
  readonly imports: readonly Line[];
  readonly body: readonly Line[];
}): string {
  const head = [BANNER, ...(parts.directive ? [parts.directive] : []), ...lines(parts.imports)];
  return `${head.join("\n")}\n\n${lines(parts.body).join("\n")}\n`;
}

/** A generated declaration (.d.ts) module: banner, imports, declarations (no blank line — dts read dense). */
export function generatedDts(parts: { readonly imports: readonly Line[]; readonly body: readonly Line[] }): string {
  return `${[DTS_BANNER, ...lines(parts.imports)].join("\n")}\n${lines(parts.body).join("\n")}\n`;
}

/**
 * An object-literal expression from declarative entries:
 * `true` → shorthand property, a string → `key: value`, falsy → omitted.
 * `obj({ schema: true, endpoint: '"/graphql"', persisted: undefined })` → `{ schema, endpoint: "/graphql" }`
 */
export function obj(entries: Record<string, string | true | false | undefined>): string {
  const parts = Object.entries(entries)
    .filter(([, v]) => v === true || (typeof v === "string" && v.length > 0))
    .map(([k, v]) => (v === true ? k : `${k}: ${v}`));
  return `{ ${parts.join(", ")} }`;
}

/** `export const <name> = <source>.<name>;` for each name — the shim re-export list. */
export function reexports(source: string, names: readonly Line[]): string[] {
  return lines(names).map((name) => `export const ${name} = ${source}.${name};`);
}

/** A JS literal (numbers, booleans, strings) for embedding a config value, or undefined to omit. */
export function literal(value: string | number | boolean | undefined): string | undefined {
  return value === undefined ? undefined : JSON.stringify(value);
}
