import { defineSchema, type OperationArtifact, type SchemaModel } from "@gleanql/core";

/** Evaluate a generated `defineSchema({...})` source string into a live SchemaModel. */
export function evalSchemaModel(src: string): SchemaModel {
  const body = src.replace(/^import[^\n]*\n/m, "").replace(/^export const schema: SchemaModel =/m, "return ");
  return new Function("defineSchema", body)(defineSchema) as SchemaModel;
}

/**
 * The portable data module `@gleanql/client/generated/operations.js`: the compiled
 * `operations` map + `schema`. No request-scoped `graph` accessor here, so it has
 * NO framework import — safe to import from client components (islands).
 */
export function genOperationsJs(
  operations: Record<string, OperationArtifact>,
  readMask?: Record<string, readonly string[]>,
): string {
  const factories: string[] = [];
  const entries: string[] = [];
  for (const [name, op] of Object.entries(operations)) {
    factories.push(op.variablesFactory.source.replace(/^export\s+/, ""));
    entries.push(
      `  ${JSON.stringify(name)}: { name: ${JSON.stringify(op.name)}, kind: ${JSON.stringify(op.kind)}, ` +
        `document: ${JSON.stringify(op.document)}, hash: ${JSON.stringify(op.hash)}, ` +
        `variables: ${op.variablesFactory.exportName}, readMap: ${JSON.stringify(op.readMap)}, ` +
        `selection: ${JSON.stringify(op.selection)} },`,
    );
  }
  // Only emitted when read-masking is on — the mask is a dev diagnostic, not
  // something every production bundle should carry.
  const mask = readMask ? `\nexport const readMask = ${JSON.stringify(readMask)};\n` : "";
  return `// GENERATED by @gleanql/vite — do not edit.
export { schema } from "./schema-model.js";

${factories.join("\n")}

export const operations = {
${entries.join("\n")}
};
${mask}`;
}

/**
 * The persisted-operations manifest: `{ "<sha256>": "<document>" }`, sorted by
 * hash for a stable diff. Upload/sync this to a separately-deployed GraphQL
 * server so it accepts exactly the operations this build can send.
 */
export function genPersistedManifest(operations: Record<string, OperationArtifact>): string {
  const entries = Object.values(operations)
    .map((op) => [op.hash, op.document] as const)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return JSON.stringify(Object.fromEntries(entries), null, 2) + "\n";
}

/** Types for the client-safe `@gleanql/client/operations` entrypoint. */
export function genOperationsDts(masking?: boolean): string {
  const mask = masking ? `export declare const readMask: Record<string, readonly string[]>;\n` : "";
  return `// GENERATED — do not edit.
import type { CompiledOperation } from "../src/index.js";
import type { SchemaModel } from "@gleanql/core";
export declare const operations: Record<string, CompiledOperation>;
export declare const schema: SchemaModel;
${mask}`;
}
